services:
  postgres:
    image: postgres:latest
    shm_size: 128mb
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5400:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - bootcamp_network
    user: ${POSTGRES_USER}

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5055:80"
    depends_on:
      - postgres
    networks:
      - bootcamp_network

volumes:
  postgres_data:

networks:
  bootcamp_network:
